# toml-docs-start lang-main
[vi]
    languageName = "Tiếng Việt"
    contentDir = "content"
    weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
    [vi.params.head]
        tagline = "Uy Tín Chất Lượng"
    [vi.params.social]
        title = "Kho Sàn Gỗ Nhập Khẩu"
        caption = "Hotline / zalo : 0966171436"
    [vi.params.footer]
        license = " Licensed under Creative Commons "
# toml-docs-end lang-param
    [vi.params.sections.san-go-cong-nghiep]
        reference = "Xem Tất Cả Sản Phẩm"
    [vi.params.sections.san-go-xuong-ca]
        reference = "Xem Tất Cả Sản Phẩm"
        [vi.params.sections.gallery]
        reference = "Xem Tất Cả Dự Án"
