name = "Hinode"
license = "MIT"
licenselink = "https://github.com/gethinode/hinode/blob/main/LICENSE"
description = "A clean documentation and blog theme."

tags = ["blog", "documentation", "minimal", "modern"]
features = ["security aware", "fast by default"]
min_version = "0.134.0"

[author]
  name = "Mark Dumay"
  homepage = "https://github.com/"